In [1]:
import pandas as pd
import numpy as np
from numpy import array

from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
df = pd.read_csv("Betelguese_120days_Cleaned.csv")

df.head()

Unnamed: 0  Visual Magnitude  Days before today
0         0.0          1.624000                0.0
1         1.0          1.596875                1.0
2         2.0          1.562083                2.0
3         3.0          1.629412                3.0
4         4.0          1.615000                4.0

In [3]:
data = df["Visual Magnitude"]

type(data)

pandas.core.series.Series

In [4]:
data = data.to_numpy(dtype ='float32')

type(data)

numpy.ndarray

In [5]:
data = np.flipud(data) 

In [6]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [7]:
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(data, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[0.75 0.75 0.4 ] 0.5
[0.75 0.4  0.5 ] 0.8
[0.4 0.5 0.8] 0.55
[0.5  0.8  0.55] 0.65
[0.8  0.55 0.65] 0.5
[0.55 0.65 0.5 ] 0.7
[0.65 0.5  0.7 ] 0.75
[0.5  0.7  0.75] 0.5
[0.7  0.75 0.5 ] 0.25
[0.75 0.5  0.25] 0.4
[0.5  0.25 0.4 ] 0.4
[0.25 0.4  0.4 ] 0.65
[0.4  0.4  0.65] 0.65
[0.4  0.65 0.65] 0.6
[0.65 0.65 0.6 ] 0.6666667
[0.65      0.6       0.6666667] 0.6
[0.6       0.6666667 0.6      ] 0.6
[0.6666667 0.6       0.6      ] 0.6
[0.6 0.6 0.6] 0.6
[0.6 0.6 0.6] 0.3
[0.6 0.6 0.3] 0.55
[0.6  0.3  0.55] 0.55
[0.3  0.55 0.55] 0.6
[0.55 0.55 0.6 ] 0.6
[0.55 0.6  0.6 ] 0.65
[0.6  0.6  0.65] 0.6
[0.6  0.65 0.6 ] 0.6
[0.65 0.6  0.6 ] 0.6
[0.6 0.6 0.6] 0.5
[0.6 0.6 0.5] 0.56666666
[0.6        0.5        0.56666666] 0.73333335
[0.5        0.56666666 0.73333335] 0.99
[0.56666666 0.73333335 0.99      ] 0.3
[0.73333335 0.99       0.3       ] 0.73
[0.99 0.3  0.73] 0.7
[0.3  0.73 0.7 ] 0.7
[0.73 0.7  0.7 ] 0.725
[0.7   0.7   0.725] 0.65
[0.7   0.725 0.65 ] 0.7
[0.725 0.65  0.7  ] 0.575
[0.65  0.7   0.5

In [8]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [9]:
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [15]:
# fit model
history = model.fit(X, y, epochs=200, verbose=0)

In [12]:
# demonstrate prediction
x_input = array([1.6294118, 1.5620834, 1.596875])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[1.6252863]]


In [16]:
# list all data in history
print(history.history.keys())

dict_keys(['loss'])


In [17]:
history.history['loss']

[0.01961309601850554,
 0.019652779448498674,
 0.019640400701639603,
 0.019667345878421044,
 0.01966433583118883,
 0.019654282007594497,
 0.01961476460960852,
 0.01961295850270865,
 0.019629065897695874,
 0.0196936201228171,
 0.019666596778294666,
 0.019711592956921275,
 0.01971562956238077,
 0.019662309590042854,
 0.01962133590765551,
 0.01961510890752685,
 0.019620047875863758,
 0.019619740393697,
 0.01959223752258485,
 0.019627963047043808,
 0.019667498222520563,
 0.0197087692343915,
 0.019642388695204745,
 0.019602684392815546,
 0.01965654493138498,
 0.019623907865817043,
 0.019594224321903015,
 0.019698691991518955,
 0.019741546641401694,
 0.019670227947993342,
 0.01961072644560921,
 0.019663224351548013,
 0.019626867304853843,
 0.019646548102198003,
 0.019671090663138296,
 0.019606184619827334,
 0.01959681780185221,
 0.019611630994243685,
 0.01960945652709121,
 0.01960981682221703,
 0.01957710433852713,
 0.019592373346795842,
 0.019626211317978343,
 0.019591810536526498,
 0.019596